import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import * as serviceWorker from './serviceWorker';
import 'bootstrap/dist/css/bootstrap.min.css';
import App from './HandleEvents/Inline-binding';
import Counter from './conditional-statement/counter';
// import Calc_Nums from './App';
//ReactDOM.render(<div className="w-50 mx-auto borderblack"><Calc_Nums /></div>, document.getElementById('root'));
ReactDOM.render(<App />,document.getElementById('root'));
ReactDOM.render(<Counter />, document.getElementById('counter'));
serviceWorker.unregister();